[package]
name = "no_proto"
license = "MIT"
version = "0.1.2"
description = "Faster than JSON with Schemas and Native Types.  Like Mutable Protocol Buffers with Compile Free Schemas."
homepage = "https://github.com/ClickSimply/NoProto"
repository = "https://github.com/ClickSimply/NoProto"
documentation="https://docs.rs/crate/no_proto/"
authors = ["Scott Lott <me@scottlott.com>"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
