[package]
name = "no_proto"
license = "MIT"
version = "0.0.0-beta.2"
description = "High Performance Serialization Library"
homepage = "https://github.com/ClickSimply/NoProto"
repository = "https://github.com/ClickSimply/NoProto"
documentation="https://docs.rs/crate/no_proto/"
authors = ["Scott Lott <me@scottlott.com>"]
readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.2"
