[package]
name = "no_proto"
license = "MIT"
version = "0.0.0-beta.1"
description = "High Performance Serialization Library"
homepage = "https://github.com/ClickSimply/NoProto"
repository = "https://github.com/ClickSimply/NoProto"
authors = ["Scott Lott <me@scottlott.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json = "0.12.2"
rand = "0.7.3"
